project:
  type: website
  output-dir: docs

website:
  title: "RNA-seq data analysis workflow"
  sidebar:
    style: "docked"
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Day One"  
        href: episode_1.qmd
        contents:
          - episode_2.qmd
          - episode_3.qmd
          - episode_4.qmd
      - section: "Day Two" 
        href: day_2_overview.qmd 
        contents:
          - episode_5.qmd
          - episode_6.qmd
      - section: "Supplementary"
        contents:
        - href: supplementary_1.qmd
          text: Supplementary 1 - Quantile Normalisation


format:
  html:
    theme: zephyr
    css: styles.css
    navigation: true

